apiVersion: v1
kind: Service
metadata:
  name: ${{ secrets.IMAGE_NAME }}
spec:
  type: NodePort
  selector:
    app: ${{ secrets.IMAGE_NAME }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
