name: Build, Push, and Deploy to Koob

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   name: Build and Push Docker Image 
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
            
  #     - name: Set up QEMU 
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3 
        
  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with: 
  #         platforms: linux/arm64
  #         push: true
  #         tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.run_number }}

      
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     platforms: linux/arm64
      #     push: true
      #     tags: triquenguyen/pi-test:0.0.5

      # - name: Build and push Docker image
      #   run: docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_VERSION }} --push .

  deploy:
    name: Deploy to Koob cluster
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.K3S_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
        
      - name: Check cluster
        run: |
          export KUBECONFIG=${HOME}/.kube/config
          kubectl get nodes -o wide


      # - name: Deploy App (Deployment)
      #   run: kubectl apply -f .github/k8s/deployment.yaml --validate=false

      # - name: Deploy App (Service)
      #   run: kubectl apply -f .github/k8s/service.yaml --validate=false

