name: Build, Push, and Deploy to Koob

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Koob cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.K3S_CONFIG }} | base64 --decode > ~/.kube/config
          export KUBECONFIG=~/.kube/config

      - name: Check cluster
        run: kubectl get nodes  